# Generated by Django 2.1.5 on 2019-10-12 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openiddemoproject', '0003_auto_20191009_0311'),
    ]

    operations = [
        migrations.AddField(
            model_name='currentsession',
            name='username',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
